services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554" # RTSP
      - "1935:1935" # RTMP
      - "8888:8888" # HLS
      - "8889:8889" # WebRTC (HTTP/WHIP/WHEP)
      - "8189:8189/udp" # WebRTC ICE/UDP
      - "8189:8189/tcp" # WebRTC ICE/TCP
    environment:
      # Enable WebRTC
      - MTX_WEBRTC=yes
      - MTX_WEBRTCADDRESS=:8889
      - MTX_WEBRTCLOCALUDPADDRESS=:8189
      - MTX_WEBRTCADDITIONALHOSTS=192.168.50.6,100.107.192.52
    restart: unless-stopped

  ffmpeg:
    image: linuxserver/ffmpeg:latest
    container_name: ffmpeg
    depends_on:
      - mediamtx
    devices:
      - /dev/video0:/dev/video0
    group_add:
      - video
    command: >
      -f v4l2 -i /dev/video0
      -c:v libx264 -preset ultrafast -tune zerolatency
      -c:a aac -f flv rtmp://mediamtx:1935/mystream
    restart: unless-stopped
